'use client'

import Image from 'next/image'
import { useState } from 'react'
import { submitRSVP } from './actions/rsvp'

const chapters = [
  { date: 'July 15, 2024', title: 'Where It All Started', image: '/story/started.jpeg', caption: 'One moment. Two people. The beginning of everything.', text: 'I dont think either of us knew what we were getting ourselves into when this story began. We were just two people, living our lives, not knowing that somewhere along the way, wed become such an important part of each others lives. Looking back now, this is where I see the first page of our story. And honestly, Im so glad I turned the page. Interestingly I was not even the best version of me and still...' },
  { date: 'February 14, 2025', title: 'Our First Valentine', image: '/story/valentines.jpeg', caption: 'The first of many little celebrations of us.', text: 'Our first Valentines Day will always be special to me because it was one of those moments where it really started to feel like there was an us. It wasnt about making everything perfect. It was simply about having each other, making a memory, and getting to celebrate what we were becoming. Little did we know wed have so many more memories to add to this story. Your dumbass was camera shy PassThrough, haha.' },
  { date: 'May 03, 2025', title: 'The First of Possible Many', image: '/story/sundayout.jpeg', caption: 'A weekend drive with you (and friends but ni wewe nilikuwa naona tu.), but one I wouldnt mind repeating a hundred times.', text: 'This is still one of my best memories of us. I drove you and my friends around and we had fun that day. We took pictures of each other later and we were so happy we did not even see the time moving. I would like to do more of these with you, nitanunua gari at this point because youd make such a pretty passenger princess.' },
  { date: 'May 17, 2025', title: 'The Way I See You', image: '/story/spurdate.jpeg', caption: 'My favorite picture of my favorite person.', text: 'I have so many pictures of you, but theres something about this one that makes me stop every time. Maybe its your expression. Maybe its the way you look without even trying. Or maybe its simply because I already know the person behind the picture. To everyone else, its just a photograph. To me, its a little reminder of just how beautiful you are, inside and out. Funny thing is before this, you were mad at me.' },
  { date: 'June 27, 2025', title: 'You Taught Me Love', image: '/story/mirrors.jpeg', caption: 'I thought I knew what love meant. Then I met you.', text: 'Before you, I had my own idea of what love was supposed to look like. Then you came into my life and slowly changed that understanding. You showed me that love isnt just the big romantic moments. Its checking on each other. Its patience. Its laughing until our stomachs hurt. Its being there on the good days and the difficult ones. Its choosing each other even when things arent perfect. You made me realise that real love is something you build, one little moment at a time.' },
  { date: 'June 29, 2025', title: 'That Smile', image: '/story/happy.jpeg', caption: 'If happiness had a face, Id know exactly where to find it.', text: 'Your smile is one of those things I dont think Ill ever get tired of seeing. Theres something about it that changes the entire atmosphere around you. And maybe you dont even realise how much it affects me. But I do. Ive seen that smile on good days, silly days, unexpected days, and days when you probably didnt even feel like smiling. And every single time, I find myself falling for you a little more.' },
  { date: 'August 08, 2025', title: 'One Year of Us', image: '/story/firstannie.jpeg', caption: 'One year down. A lifetime of memories ahead.', text: 'Somehow, we made it to one year. When I look back at everything that happened before this moment, I realise just how much can change in a year. We had laughed together, learned each other, made mistakes, made memories, and grown closer through it all. Our first anniversary wasnt just a celebration of the year wed completed. It was a celebration of everything we had become together.' },
  { date: 'November 02, 2025', title: 'Our Kind of Crazy', image: '/story/crazy.jpeg', caption: 'Normal is overrated anyway.', text: 'I genuinely dont know how two people can be this ridiculous and somehow make it work so well. 😂 But thats one of the things I love about us. We can be serious when we need to be, but we can also completely lose our minds together. The random jokes, the weird moments, the things that would make absolutely no sense to anyone else, those are some of my favorite memories. I wouldnt trade our kind of crazy for anything.' },
  { date: 'December 20, 2025', title: 'Its the Little Things', image: '/story/howyoulookatme.jpeg', caption: 'You have a way of making ordinary moments feel special.', text: 'One thing Ive come to appreciate more and more about you is how thoughtful you are. Sometimes its something big, and sometimes its something so small that you probably dont even realise Ive noticed. But I notice. I notice the little gestures, the way you think about me, the things you remember, and the effort you put into making me happy. Those moments may seem small, but theyre some of the biggest reasons I feel loved by you.' },
  { date: 'January 03, 2026', title: 'Celebrating You', image: '/story/birthday.jpeg', caption: 'Your day, your smile, and another memory Ill always keep.', text: 'Your birthday gave me another excuse to celebrate one of my favorite people in the world. Seeing you happy, seeing that smile, and getting to be part of your special day meant more to me than you probably realised. I hope you always know that you deserve to be celebrated, not just on your birthday, but on all the ordinary days in between. And selfishly, I hope I get to be there for many, many more of them.' },
  { date: 'July 30, 2026', title: 'Two years, and still my favorite story', image: '/story/2years.jpeg', caption: 'Two years of choosing each other, in all the beautiful ordinary ways.', text: 'Thank you for making a life with me that feels both grounded and full of surprise. Here is to the pages we have written, and to all the blank ones waiting for us.' },
]

export default function Home() {
  const [index, setIndex] = useState(0)
  const [showRSVP, setShowRSVP] = useState(false)
  const [sent, setSent] = useState(false)
  const [busy, setBusy] = useState(false)
  const chapter = chapters[index]
  function next() { if (index === chapters.length - 1) setShowRSVP(true); else setIndex(index + 1) }
  function previous() { setShowRSVP(false); setIndex(Math.max(0, index - 1)) }
  async function send(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); const data = new FormData(e.currentTarget); const result = await submitRSVP({ preferredDate: String(data.get('preferredDate') || ''), preferredTime: String(data.get('preferredTime') || '') }); setBusy(false); if (result.ok) setSent(true) }
  return <main className="story-shell"><header className="topbar"><span className="brand">A little story about us</span><span className="chapter-count">{showRSVP ? 'The next page' : `${String(index + 1).padStart(2, '0')} / ${String(chapters.length).padStart(2, '0')}`}</span></header><section className={`story-page ${showRSVP ? 'rsvp-page' : ''}`}><div className="story-art">{showRSVP ? <div className="rsvp-mark">with love,<br /><em>always</em></div> : <Image src={chapter.image} alt={chapter.caption} fill priority={index === 0} sizes="(max-width: 800px) 100vw, 48vw" />}</div><div className="story-copy">{showRSVP ? sent ? <><p className="eyebrow">It is on my plate now</p><h1>I will see you there.</h1><p className="lead">Your reply made its way to me. Thank you for being part of our story.</p></> : <><p className="eyebrow">One more little thing</p><h1>Will you celebrate with me?</h1><p className="lead">Tell me which date and time would feel best. I will take care of the rest. No pressure</p><div className="event-links"><a href="https://www.instagram.com/ate.ke/?hl=en" target="_blank" rel="noreferrer">View the place <span>↗</span></a><a href="https://www.ate.co.ke/menus" target="_blank" rel="noreferrer">See the menu <span>↗</span></a></div><form onSubmit={send}><label className="field-label" htmlFor="preferredDate">Preferred date</label><input id="preferredDate" name="preferredDate" type="date" required /><label className="field-label" htmlFor="preferredTime">Preferred time</label><input id="preferredTime" name="preferredTime" type="time" required /><button disabled={busy} type="submit">{busy ? 'Sending…' : 'Save my preference'}</button></form></> : <><p className="eyebrow">{chapter.date}</p><h1>{chapter.title}</h1><p className="caption">{chapter.caption}</p><div className="rule" /><p className="body-copy">{chapter.text}</p></>} {!sent && <nav className="story-nav"><button onClick={previous} disabled={index === 0 && !showRSVP} aria-label="Previous page">← <span>Previous</span></button><button onClick={next} aria-label={showRSVP ? 'Finish' : 'Next page'}>{showRSVP ? 'Close' : 'Next'} <span>→</span></button></nav>}</div></section><footer className="footer-note">made of small moments <span>·</span> and a lot of love</footer></main>
}
